server:
  port 8080
application:
  context-path: /simples-dental-api/v1
spring:
  application:
    name: simples-dental-api
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

